### ISSUE TITLE
Strange menu scrollbar behavior on Svelte docs page

### ISSUE THREAD

**Issue by testrocket** [sveltejs/site-kit#20]
**Steps to reproduce**:
1. Go to https://svelte.dev/docs.
2. Scroll down left menu either by mouse wheel or trackpad.
3. Move cursor away from the menu.
4. Result: scrollbar goes back to the top by itself.

You can also try changing scrollbar position simply by dragging. Then move mouse cursor over menu  and again away from it.
On Chrome scrollbar goes back smoothly and on Safari it jumps back to the top.

**Expected behavior**:
Scrollbar should not return to the top by itself.

**Comment by benmccann** [comment]
This was very confusing and unexpected to me and I thought it was a bug
