### ISSUE TITLE
Cannot interact with the scrollbar in kit.svelte.dev/docs

### ISSUE THREAD

**Issue by ankified** [sveltejs/site-kit#276]
The issue happens in the vertical scrollbar for the text but not for the menu. I can only scroll the page using the trackpad or keyboard arrows, but not by clicking the scrollbar. 

I noticed this issue while using both MS Edge and Brave browsers, and it happens in svelte.dev/docs as well as in kit.svelte.dev/docs.

**Comment by Zyphdoz** [comment]
I've experienced this too. In case people are unable to reproduce I can add that this only happens for me when the viewport is between 1200-1446px wide.

**Comment by benmccann** [comment]
I can't reproduce any issue with my viewport at 1300px, so assume it was fixed when the site was rewritten
