### ISSUE TITLE
Incompatible with `marked` version 13

### ISSUE THREAD

**Issue by benmccann** [sveltejs/site-kit#296]
`heading` has new arguments in marked 13

https://github.com/sveltejs/site-kit/blob/12fdd45d53f112c8fcc5ff754b23b549d404aeb1/packages/site-kit/src/lib/markdown/renderer.js#L228

![Screenshot from 2024-06-12 08-23-45](https://github.com/sveltejs/site-kit/assets/322311/5e23a156-831d-4d19-a95e-c707f4bff0b8)

**Comment by UziTech** [comment]
default_renderer will also have to be updated to accept tokens

https://github.com/sveltejs/site-kit/blob/12fdd45d53f112c8fcc5ff754b23b549d404aeb1/packages/site-kit/src/lib/markdown/utils.js#L91
