### ISSUE TITLE
Local & Session Storage not working 

### ISSUE THREAD

**Issue by ktryndchrs** [sveltejs/site-kit#34]
**1/6 The Project**
[Project.zip](https://github.com/sveltejs/site-kit/files/5783125/Project.zip)

**2/6 Package content**
```
{
	"name": "svelte-next2",
	"version": "0.0.1",
	"scripts": {
		"dev": "svelte-kit dev",
		"build": "svelte-kit build",
		"start": "svelte-kit start"
	},
	"devDependencies": {
		"@snowpack/plugin-postcss": "^1.0.11",
		"@sveltejs/adapter-node": "next",
		"@sveltejs/kit": "next",
		"@sveltejs/snowpack-config": "next",
		"autoprefixer": "^10.2.0",
		"cssnano": "^4.1.10",
		"postcss": "^8.2.2",
		"postcss-cli": "^8.3.1",
		"postcss-load-config": "^3.0.0",
		"postcss-preset-env": "^6.7.0",
		"sass": "^1.0.0",
		"svelte": "^3.29.0",
		"svelte-preprocess": "^4.6.1",
		"tailwindcss": "^2.0.2"
	},
	"dependencies": {
		"svelte-i18n": "^3.3.0" // not loaded in my code
	}
}

```

**3/6 Display the following error in the browser**
> **500**
> Unexpected identifier
> SyntaxError: Unexpected identifier
>   at new Function (<anonymous>)
>   at initialize_module (/Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/loader.js:123:81)
>   at /Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/loader.js:112:21
>   at async Promise.all (index 1)
>   at initialize_module (/Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/loader.js:110:8)
>   at /Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/loader.js:112:21
>   at async Promise.all (index 1)
>   at initialize_module (/Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/loader.js:110:8)
>   at /Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/api/dev/index.js:306:32
>   at get_response (/Users/catherine/Sites/svelte-next2/node_modules/@sveltejs/kit/src/renderer/page.js:128:15)

**4/6 The header response**
> SyntaxError: Unexpected identifier
> HTTP/1.1 500 Internal Server Error
> content-type: text/html
> Date: Thu, 07 Jan 2021 17:36:07 GMT
> Connection: keep-alive
> Keep-Alive: timeout=5
> Transfer-Encoding: chunked

**5/6 Request Header**
> GET / HTTP/1.1
> Host: localhost:3000
> User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 11.1; rv:85.0) Gecko/20100101 Firefox/85.0
> Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
> Accept-Language: en-US,en;q=0.5
> Accept-Encoding: gzip, deflate
> Connection: keep-alive
> Upgrade-Insecure-Requests: 1
> Pragma: no-cache
> Cache-Control: no-cache

**6/6 Additional note**
This work in the "regular" sveltejs

**Comment by benmccann** [comment]
This looks to be from a pre-release version of SvelteKit. These definitely work in SvelteKit 1.0 and 2.0
